### PR TITLE
contact us updated

### PR DESCRIPTION
**Pull request by Sushilverma002**
now it get fixed and issue-> #572 is solved.
please review it.
image

### CODE REVIEW

**Comment by NageshMandal** [comment]
resolve the conflicts

**Comment by Sushilverma002** [comment]
done

**Comment by Sushilverma002** [comment]
@NageshMandal

**Comment by Sushilverma002** [comment]
@NageshMandal now conflict is resolved please merge it.

**Comment by Sushilverma002** [comment]
@NageshMandal please merge it , And review.

**Comment by Sushilverma002** [comment]
@NageshMandal please merge it

**Pull request closed without merging**
