### PR TITLE
Improve the alignment of navbar and make it responsive  and added transitions in it

### LINKED ISSUE #701: Want to make navbar responsive with a hamburgur icon and animations
The nav bar is not responsive so i want tomake it responsive and will add a hamburrger icon for  which will appear when website will run in small devices and also i will add transition in it so that on clicking the hamburger the navbar will com out with a transition
so @NageshMandal  Please assign me this issue

### PR DESCRIPTION
**Pull request by lakhan06**
I improve the allignment of navbar and also make it responsive and add a hamburger icon so that at small screens navbar will come by clicking on hamburger icon.
Close #701 

**Screenshot**

image

**Demo Video**

https://github.com/NageshMandal/Engineering-Notes-Website/assets/119161467/4d07c4a2-ff6d-419f-9aac-186a4862b7f6

@NageshMandal  Please accept my pull request

### CODE REVIEW

**Comment by lakhan06** [comment]
@NageshMandal I am writing to kindly request your attention and consideration in reviewing and accepting my pull request. I would greatly appreciate it if you could allocate some time to review the pull request and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly.
Thank You

**Comment by NageshMandal** [comment]
the navbar is looking good but the are many errors 
the heading and paragraph is not align properly the old alignment is good please follow the old alignment

**Comment by NageshMandal** [comment]
the three line menu should visible when we open the website in mobile

**Comment by NageshMandal** [comment]
font should normal not bold

**Comment by lakhan06** [comment]
> font should normal not bold

ok

**Comment by lakhan06** [comment]
@NageshMandal  I made all the changes you want and i maintain the old alignment and hamburger now is visable for small screen and font is not also bold.So i request  you to review and accept my pull request

**Comment by lakhan06** [comment]
@NageshMandal Please merge it or if their some more changes need then please tell me i will do that

**Comment by lakhan06** [comment]
@NageshMandal Please merge my pull request it will be very helfull for me

**Pull request closed without merging**
