### PR TITLE
Update footer

### PR DESCRIPTION
**Pull request by varsha-saini02**
I fix the issue #24 
1. Update the footer make it more readable by changing the font size and alignment.
2. Changed the background to black & white gradient to match the rest of the theme of website and the light & dark mode as well.
3.  Broaden the headings and add hover effect to the anchor tags of footer.
4.  Add respective color to the social icons.

Thank you.

### CODE REVIEW

**Comment by varsha-saini02** [comment]
Changed the footer to this. Change the alignment and font-size to make it more readable and matched the bg with the rest of the website.

foooter3



Make the anchor tags of footer more readable

footer2


Add the respective colors to the social icons

foooter1

**Comment by varsha-saini02** [comment]
Changed the color combination of footer  with the colors already present in website.
footer

**Comment by varsha-saini02** [comment]
Update the changes
footer-1

**Comment by NageshMandal** [comment]
Now It's Looking Awesome🤩

**Pull request merged**
