### PR TITLE
Added Scroll reveal effect

### LINKED ISSUE #787: Revealing effect animation on scrooling
I want to add revealing animation effect in which headings and cards or images come with a revealing animation effect on scrolling.
I will enhance the user experience and will give website a modern look.

SO @NageshMandal Sir I request you to assign me this issue

### PR DESCRIPTION
**Pull request by lakhan06**
I added a  scroll revealing animation effect in which headings and cards or images come with a revealing animation effect on scrolling.
I will enhance the user experience and will give website a modern look.
Closes #787 

https://github.com/NageshMandal/Engineering-Notes-Website/assets/119161467/14b69771-0292-4006-9cee-4523fc32ed3c

https://github.com/NageshMandal/Engineering-Notes-Website/assets/119161467/7ee0737b-6e43-49fb-8d5f-440ebed9fe77

@NageshMandal Please Merge my pull request it will give the website a modern look

### CODE REVIEW

**Comment by lakhan06** [comment]
@NageshMandal Please Merge this Pull request

**Comment by NageshMandal** [comment]
https://github.com/NageshMandal/Engineering-Notes-Website/assets/106006006/f70059a7-fbdd-4b10-b556-8bb9c407d59e

Not Working Properly

**Comment by lakhan06** [comment]
@NageshMandal Sir I solved the error You can check now 


https://github.com/NageshMandal/Engineering-Notes-Website/assets/119161467/36e1576e-dd94-436d-9d37-f9180ab9c84c

**Comment by lakhan06** [comment]
@NageshMandal  please merge my pull request

**Pull request closed without merging**
