### PR TITLE
[GSSoC'23] Updating Input box and Search button of Navbar

### LINKED ISSUE #617: [GSSoC'23] Adding more attractive navbar search button and input box
Description

- Adding responsive effect on the search button using js
- Button will comes up when types something inside the text box
- Responsive effect of input box with lightening effect
- Showing a pop effect will increase the attractiveness of the website

Adding these effects will result in the more attractive user interface and experience for the users.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
Close issue fixes #617 

# Desctiption

- Adding responsive effect on the search button
- Input field will comes up when click on search button
- Responsive effect of input box with lightening effect
- Showing a pop effect is increasing the attractiveness of the website
- Adding a shadow effect on button and input box both

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@NageshMandal please review this pull request and requested to merge it into the main branch of this repository for a successful contribution under GSSoC'23 program

**Comment by NageshMandal** [comment]
Resolve the conflict

**Comment by NageshMandal** [comment]
all the input fields are changed 
some forms are also changed due to the search box

**Comment by Avdhesh-Varshney** [comment]
@NageshMandal please again review the changes and requested to merge it into the main branch for a valuable contribution under GSSoC'23 program

**Comment by NageshMandal** [comment]
https://github.com/NageshMandal/Engineering-Notes-Website/assets/106006006/fa42412b-1c23-45fe-b663-dade65ec4881

**Comment by Avdhesh-Varshney** [comment]
@NageshMandal please again review this pull request.
I have done all the changes in a proper way as you have said.
Please merge this pr for a successful contribution under GSSoC'23 program

**Comment by Avdhesh-Varshney** [comment]
@NageshMandal please review this pull request

**Pull request closed without merging**
