### PR TITLE
Revert "dark mode stays on refresh"

### PR DESCRIPTION
**Pull request by NageshMandal**
Reverts NageshMandal/Engineering-Notes-Website#15
it is not working fix it

### CODE REVIEW

**Comment by MufaddalHakim** [comment]
what is not working right?

**Comment by NageshMandal** [comment]
05 10 2022_11 44 28_REC

**Comment by NageshMandal** [comment]
The image should overlap each other

**Comment by MufaddalHakim** [comment]
when does this occur?

**Pull request merged**
