### PR TITLE
CEC Section card design changed

### PR DESCRIPTION
**Pull request by Sameep002**
CEC Section card design changed and border radius added.
On hovering the cards the branch related info is shown 

Screenshot 2023-05-21 122628

### CODE REVIEW

**Comment by NageshMandal** [comment]
resolve the conflicts

**Comment by rafiya2003** [comment]
can I work on this?

**Comment by Sameep002** [comment]
@NageshMandal resolved the conflicts 👍

**Comment by Sameep002** [comment]
Screenshot 2023-05-23 145551

last time also same came with no conflicts!!!

**Comment by NageshMandal** [comment]
https://github.com/NageshMandal/Engineering-Notes-Website/assets/106006006/e19767d8-646c-4897-9cfb-6a47a319ea63

**Comment by Sameep002** [comment]
i take the latest code files n try again. do i create new branch?

**Comment by NageshMandal** [comment]
yes

**Pull request closed without merging**
