### PR TITLE
Added Notes of 1st semester for computer science branch and also make the footer same for all pages according to home page 

### PR DESCRIPTION
**Pull request by lakhan06**
Dear @NageshMandal  sir I like to inform you that I added 1st semester notes for computer science branch and also make the footer of all pages same as they are not same in all according to home page.
I  request your attention and consideration in reviewing and accepting my pull request.

WhatsApp Image 2023-05-21 at 15 46 26

### CODE REVIEW

**Comment by NageshMandal** [comment]
21 05 2023_15 58 28_REC
21 05 2023_15 58 51_REC

**Comment by NageshMandal** [comment]
resolve this issues

**Comment by lakhan06** [comment]
> resolve this issues

ok sir

**Comment by lakhan06** [comment]
Dear @NageshMandal sir i have resolved the issues

**Pull request closed without merging**
