### PR TITLE
 Adding AI Chat and Voice Assistant for FAQ, Navigation, and User Experience Improvement

### PR DESCRIPTION
**Pull request by Nishitbaria**
This pull request introduces an AI Chat and Voice Assistant to the Web3 Expense Tracker website, enhancing the user experience by providing support for Frequently Asked Questions (FAQ), page navigation, and overall user interaction.

### Changes Made

1. Integrated an AI Chat and Voice Assistant feature using a suitable library or API to provide interactive support to users visiting the college website.
2. Added necessary JavaScript code to initialize and handle the AI Chat and Voice Assistant on relevant pages.
3. Designed a chat interface that allows users to interact with the AI Assistant and receive instant responses to their queries.
4. This assistant  to address common user queries and provide instant responses using the AI Assistant.
5. Configured the AI Assistant to handle user queries related to page navigation, helping users quickly find the desired information or sections within the website.
6. Implemented voice recognition functionality, if feasible, to allow users to interact with the AI Assistant using voice commands or questions.
7. Ensured error handling and fallback mechanisms are in place to handle unexpected queries or cases where the AI Assistant is unable to provide a satisfactory response.
8. Conducted thorough testing to ensure the AI Chat and Voice Assistant functions correctly, responds accurately to user queries, and enhances the overall user experience.

 ## screenshots

**VIDEO**

[video](https://github.com/NageshMandal/Engineering-Notes-Website/assets/85815172/58afbbe3-1de0-4af1-9fe0-ea51eb13eb80)

### CODE REVIEW

**Comment by Nishitbaria** [comment]
@NageshMandal ,please reviwe my pull request

**Comment by Nishitbaria** [comment]
@NageshMandal ,please review my pull request

**Comment by Nishitbaria** [comment]
@NageshMandal ,please review my pull request

**Comment by Nishitbaria** [comment]
@NageshMandal ,please review and merge pull request

**Comment by NageshMandal** [comment]
07 07 2023_23 46 31_REC
align it up

**Comment by Nishitbaria** [comment]
https://github.com/NageshMandal/Engineering-Notes-Website/assets/85815172/b9aee1d9-d814-4c9e-894f-c0f4a48e6f02

@NageshMandal ,First thing it is movable and i have fixed default position of it to left bottom,please check and merge

**Comment by NageshMandal** [comment]
resolve the conflicts

**Comment by Nishitbaria** [comment]
@NageshMandal ,please review and merge my pull request,i haved resolved conflicts,please merge it ,otherwise more conflicts can occur

**Comment by Nishitbaria** [comment]
@NageshMandal ,please review and merge this

**Comment by Nishitbaria** [comment]
@NageshMandal ,please review and merge my pull request,i haved resolved conflicts,please merge it ,otherwise more conflicts can occur

**Comment by Nishitbaria** [comment]
@NageshMandal ,please review and merge this

**Comment by Nishitbaria** [comment]
@NageshMandal ,please review and merge this

**Comment by Nishitbaria** [comment]
@SurajPratap10 ,please review and merge my pull request  ,please reply

**Pull request closed without merging**
