### PR TITLE
fixed navbar bug and added more styles in footer

### PR DESCRIPTION
**Pull request by HassanShanJava**
- Fixed Navbar error
- Changed Style in footer
- Added styles to newletter
- Added styles to links
- Added styles to profile contact

### CODE REVIEW

**Comment by HassanShanJava** [comment]
Do let me know if this is an issue, this is my first time contributing so any feedback is appreciated.

**Comment by NageshMandal** [comment]
Could you please add screen shorts so that i can see what changes you made

**Comment by HassanShanJava** [comment]
Sure here they are:
fix navbar issue

footer stling changes made

**Comment by HassanShanJava** [comment]
as you can see, I fixed your navbar, so now the logo and link are properly inline, and added multiple style changes in the footer to make it more visually pleasing.

**Comment by NageshMandal** [comment]
its looking good 🤩 well done 🌟

**Comment by HassanShanJava** [comment]
Thank you

**Pull request merged**
